dynamic data = [
  {
    "idCultivar": "1",
    "nome": "BRS 232",
    "tipoCrescimento": "determinado",
    "corFlor": "ROXA",
    "corPubescencia": "CINZA",
    "corHilo": "MARROM-CLARO",
    "teorMedioProteina": "40.90",
    "teorMedioOleo": "19.50",
    "alturaPlanta": "67cm a 93cm",
    "pesoMedio1000Sementes": "185.00",
    "potencialRamificacao": "ALTO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "RESISTENTE",
    "tipoCultivar": "CONVENCIONAL"
  },
  {
    "idCultivar": "2",
    "nome": "BRS 284",
    "tipoCrescimento": "INDETERMINADO",
    "corFlor": "ROXA",
    "corPubescencia": "CINZA",
    "corHilo": "MARROM-CLARO",
    "teorMedioProteina": "36.30",
    "teorMedioOleo": "23.50",
    "alturaPlanta": "90 CM",
    "pesoMedio1000Sementes": "146.00",
    "potencialRamificacao": "ALTO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "MODERADAMENTE RESISTENTE",
    "tipoCultivar": "CONVENCIONAL"
  },
  {
    "idCultivar": "3",
    "nome": "BRS 1054IPRO",
    "tipoCrescimento": "INDERTEMINADO",
    "corFlor": "ROXA",
    "corPubescencia": "CINZA",
    "corHilo": "MARROM-CLARO",
    "teorMedioProteina": "35.00",
    "teorMedioOleo": "22.90",
    "alturaPlanta": "95 CM",
    "pesoMedio1000Sementes": "180.00",
    "potencialRamificacao": "MÉDIO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "RESISTENTE",
    "tipoCultivar": "RR"
  },
  {
    "idCultivar": "4",
    "nome": "BRS 433RR",
    "tipoCrescimento": "INDETERMINADO",
    "corFlor": "ROXA",
    "corPubescencia": "CINZA",
    "corHilo": "MARROM-CLARO",
    "teorMedioProteina": "39.40",
    "teorMedioOleo": "20.80",
    "alturaPlanta": "95 CM",
    "pesoMedio1000Sementes": "160.00",
    "potencialRamificacao": "MÉDIO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "RESISTENTE",
    "tipoCultivar": "INTACTA"
  },
  {
    "idCultivar": "5",
    "nome": "BRS 573",
    "tipoCrescimento": "INDETERMINADO",
    "corFlor": "BRANCA",
    "corPubescencia": "CINZA",
    "corHilo": "MARROM-CLARO",
    "teorMedioProteina": "37.40",
    "teorMedioOleo": "22.10",
    "alturaPlanta": "75 CM",
    "pesoMedio1000Sementes": "157.00",
    "potencialRamificacao": "ALTO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "RESISTENTE",
    "tipoCultivar": "INTACTA"
  },
  {
    "idCultivar": "6",
    "nome": "BRS 528",
    "tipoCrescimento": "INDETERMINADO",
    "corFlor": "ROXA",
    "corPubescencia": "CINZA",
    "corHilo": "MARROM-CLARO",
    "teorMedioProteina": "36.00",
    "teorMedioOleo": "23.40",
    "alturaPlanta": "78 CM",
    "pesoMedio1000Sementes": "165.00",
    "potencialRamificacao": "MÉDIO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "RESISTENTE",
    "tipoCultivar": "INTACTA"
  },
  {
    "idCultivar": "7",
    "nome": "BRS 391",
    "tipoCrescimento": "INDETERMINADO",
    "corFlor": "BRANCA",
    "corPubescencia": "CINZA",
    "corHilo": "MARROM-CLARO",
    "teorMedioProteina": "39.30",
    "teorMedioOleo": "20.10",
    "alturaPlanta": "83 CM",
    "pesoMedio1000Sementes": "144.00",
    "potencialRamificacao": "ALTO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "RESISTENTE",
    "tipoCultivar": "INTACTA"
  },
  {
    "idCultivar": "8",
    "nome": "BRS 1074IPRO",
    "tipoCrescimento": "INDETERMINADO",
    "corFlor": "ROXA",
    "corPubescencia": "CINZA",
    "corHilo": "PRETA IMPERFEITA",
    "teorMedioProteina": "33.90",
    "teorMedioOleo": "24.40",
    "alturaPlanta": "100 CM",
    "pesoMedio1000Sementes": "160.00",
    "potencialRamificacao": "MÉDIO",
    "lancamento": "2020/2021",
    "fundacao": "FUNDAÇÃO MERIDIONAL",
    "acamamento": "RESISTENTE",
    "tipoCultivar": "RR"
  }
];